# Demyx
# https://demyx.sh

function demyx_env() {
    demyx_app_config

    [[ -z "$DEMYX_APP_CONTAINER" ]] && DEMYX_APP_CONTAINER=${DEMYX_TARGET//./_}

    if [[ "$DEMYX_RUN_TYPE" = wp ]] || [[ "$DEMYX_APP_TYPE" = wp ]]; then
        [[ -z "$DEMYX_APP_ID" ]] && DEMYX_APP_ID=$(demyx util uuidgen | awk -F '[-]' '{print $1}')
        [[ -z "$DEMYX_APP_WP_CONTAINER" ]] && DEMYX_APP_WP_CONTAINER=${DEMYX_TARGET//./}_wp_${DEMYX_APP_ID}_1
        [[ -z "$DEMYX_APP_DB_CONTAINER" ]] && DEMYX_APP_DB_CONTAINER=${DEMYX_TARGET//./}_db_${DEMYX_APP_ID}_1
        [[ -n "$DEMYX_RUN_USER" ]] && WORDPRESS_USER="$DEMYX_RUN_USER"
        [[ -n "$DEMYX_RUN_PASSWORD" ]] && WORDPRESS_USER_PASSWORD="$DEMYX_RUN_PASSWORD"
        [[ -n "$DEMYX_RUN_EMAIL" ]] && WORDPRESS_USER_EMAIL="$DEMYX_RUN_EMAIL"
        [[ -z "$DEMYX_APP_TYPE" ]] && DEMYX_APP_TYPE=wp
        [[ -z "$DEMYX_APP_PATH" ]] && DEMYX_APP_PATH="$DEMYX_WP"/"$DEMYX_TARGET"
        [[ -z "$DEMYX_APP_CONFIG" ]] && DEMYX_APP_CONFIG="$DEMYX_WP"/"$DEMYX_TARGET"/config
        [[ -z "$WORDPRESS_USER" ]] && WORDPRESS_USER=$(demyx util gpw 1 10 | sed -e 's/\r//g')
        [[ -z "$WORDPRESS_USER_PASSWORD" ]] && WORDPRESS_USER_PASSWORD=$(demyx util pwgen -cns 50 1 | sed -e 's/\r//g')
        [[ -z "$WORDPRESS_USER_EMAIL" ]] && WORDPRESS_USER_EMAIL="info@$DEMYX_TARGET"
        [[ -z "$WORDPRESS_DB_HOST" ]] && WORDPRESS_DB_HOST=$DEMYX_APP_DB_CONTAINER
        [[ -z "$WORDPRESS_DB_NAME" ]] && WORDPRESS_DB_NAME=$DEMYX_APP_CONTAINER
        [[ -z "$WORDPRESS_DB_USER" ]] && WORDPRESS_DB_USER=$DEMYX_APP_CONTAINER
        [[ -z "$WORDPRESS_DB_PASSWORD" ]] && WORDPRESS_DB_PASSWORD=$(demyx util pwgen -cns 50 1 | sed -e 's/\r//g')
        [[ -z "$MARIADB_ROOT_PASSWORD" ]] && MARIADB_ROOT_PASSWORD=$(demyx util pwgen -cns 50 1 | sed -e 's/\r//g')
        
        [[ -n "$DEMYX_RUN_SSL" ]] && DEMYX_APP_SSL="$DEMYX_RUN_SSL"
        [[ -n "$DEMYX_RUN_RATE_LIMIT" ]] && DEMYX_APP_RATE_LIMIT=on
        [[ -z "$DEMYX_APP_CACHE" ]] && DEMYX_APP_CACHE=off
        [[ -z "$DEMYX_APP_CDN" ]] && DEMYX_APP_CDN=off
        [[ -z "$DEMYX_APP_AUTH" ]] && DEMYX_APP_AUTH=off
        [[ -z "$DEMYX_APP_DEV" ]] && DEMYX_APP_DEV=off

        cat > "$DEMYX_WP"/"$DEMYX_TARGET"/.env <<-EOF
            # AUTO GENERATED
            DEMYX_APP_ID=$DEMYX_APP_ID
            DEMYX_APP_TYPE=$DEMYX_APP_TYPE
            DEMYX_APP_PATH=$DEMYX_APP_PATH
            DEMYX_APP_CONFIG=$DEMYX_APP_CONFIG
            DEMYX_APP_CONTAINER=$DEMYX_APP_CONTAINER
            DEMYX_APP_DOMAIN=$DEMYX_TARGET
            DEMYX_APP_SSL=$DEMYX_APP_SSL
            DEMYX_APP_RATE_LIMIT=$DEMYX_APP_RATE_LIMIT
            DEMYX_APP_AUTH=$DEMYX_APP_AUTH
            DEMYX_APP_CACHE=$DEMYX_APP_CACHE
            DEMYX_APP_CDN=$DEMYX_APP_CDN
            DEMYX_APP_DEV=$DEMYX_APP_DEV
            DEMYX_APP_MONITOR_THRESHOLD=3
            DEMYX_APP_MONITOR_SCALE=5
            DEMYX_APP_MONITOR_CPU=25
            DEMYX_APP_FORCE_STS_HEADER=$DEMYX_FORCE_STS_HEADER
            DEMYX_APP_STS_SECONDS=$DEMYX_STS_SECONDS
            DEMYX_APP_STS_INCLUDE_SUBDOMAINS=$DEMYX_STS_INCLUDE_SUBDOMAINS
            DEMYX_APP_STS_PRELOAD=$DEMYX_STS_PRELOAD
            DEMYX_APP_WP_CONTAINER=$DEMYX_APP_WP_CONTAINER
            DEMYX_APP_DB_CONTAINER=$DEMYX_APP_DB_CONTAINER
            WORDPRESS_USER=$WORDPRESS_USER
            WORDPRESS_USER_PASSWORD=$WORDPRESS_USER_PASSWORD
            WORDPRESS_USER_EMAIL=$WORDPRESS_USER_EMAIL
            WORDPRESS_DB_HOST=db_${DEMYX_APP_ID}
            WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
            WORDPRESS_DB_USER=$WORDPRESS_DB_USER
            WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
            MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
            MARIADB_DEFAULT_CHARACTER_SET=utf8
            MARIADB_CHARACTER_SET_SERVER=utf8
            MARIADB_COLLATION_SERVER=utf8_general_ci
            MARIADB_KEY_BUFFER_SIZE=32M
            MARIADB_MAX_ALLOWED_PACKET=16M
            MARIADB_TABLE_OPEN_CACHE=2000
            MARIADB_SORT_BUFFER_SIZE=4M
            MARIADB_NET_BUFFER_SIZE=4M
            MARIADB_READ_BUFFER_SIZE=2M
            MARIADB_READ_RND_BUFFER_SIZE=1M
            MARIADB_MYISAM_SORT_BUFFER_SIZE=32M
            MARIADB_LOG_BIN=mysql-bin
            MARIADB_BINLOG_FORMAT=mixed
            MARIADB_SERVER_ID=1
            MARIADB_INNODB_DATA_FILE_PATH=ibdata1:10M:autoextend
            MARIADB_INNODB_BUFFER_POOL_SIZE=32M
            MARIADB_INNODB_LOG_FILE_SIZE=5M
            MARIADB_INNODB_LOG_BUFFER_SIZE=8M
            MARIADB_INNODB_FLUSH_LOG_AT_TRX_COMMIT=1
            MARIADB_INNODB_LOCK_WAIT_TIMEOUT=50
            MARIADB_INNODB_USE_NATIVE_AIO=1
            MARIADB_READ_BUFFER=2M
            MARIADB_WRITE_BUFFER=2M
            MARIADB_MAX_CONNECTIONS=100
EOF
        sed -i 's/            //' "$DEMYX_WP"/"$DEMYX_TARGET"/.env
    fi
}

function demyx_stack_env() {
    if [[ -z "$DEMYX_INSTALL_FORCE" ]]; then
        if [[ -f "$DEMYX_STACK"/.env ]]; then
            DEMYX_PARSE_BASIC_AUTH=$(grep -s DEMYX_STACK_AUTH "$DEMYX_STACK"/.env | awk -F '[=]' '{print $2}' || true)
            source "$DEMYX_STACK"/.env
            DEMYX_STACK_AUTH="$DEMYX_PARSE_BASIC_AUTH"
        fi
    fi

    [[ -z "$DEMYX_STACK_RECENT_ERRORS" ]] && DEMYX_STACK_RECENT_ERRORS=100
    [[ -z "$DEMYX_STACK_DOCKER_WATCH" ]] && DEMYX_STACK_DOCKER_WATCH=true
    [[ -z "$DEMYX_STACK_DOCKER_EXPOSED_BY_DEFAULT" ]] && DEMYX_STACK_DOCKER_EXPOSED_BY_DEFAULT=false
    [[ -z "$DEMYX_STACK_ENTRYPOINT_DEFAULTENTRYPOINTS" ]] && DEMYX_STACK_ENTRYPOINT_DEFAULTENTRYPOINTS=http,https
    [[ -z "$DEMYX_STACK_ACME_ONHOSTRULE" ]] && DEMYX_STACK_ACME_ONHOSTRULE=true
    [[ -z "$DEMYX_STACK_ACME_STORAGE" ]] && DEMYX_STACK_ACME_STORAGE=/demyx/acme.json
    [[ -z "$DEMYX_STACK_ACME_ENTRYPOINT" ]] && DEMYX_STACK_ACME_ENTRYPOINT=https
    [[ -z "$DEMYX_STACK_ACME_HTTPCHALLENGE_ENTRYPOINT" ]] && DEMYX_STACK_ACME_HTTPCHALLENGE_ENTRYPOINT=http
    [[ -z "$DEMYX_STACK_LOG_LEVEL" ]] && DEMYX_STACK_LOG_LEVEL=INFO
    [[ -z "$DEMYX_STACK_LOG_ACCESS" ]] && DEMYX_STACK_LOG_ACCESS=/var/log/demyx/access.log
    [[ -z "$DEMYX_STACK_LOG_ERROR" ]] && DEMYX_STACK_LOG_ERROR=/var/log/demyx/error.log

    cat > "$DEMYX_STACK"/.env <<-EOF
        # AUTO GENERATED
        DEMYX_STACK_DOMAIN=$DEMYX_STACK_DOMAIN
        DEMYX_STACK_AUTH=$DEMYX_PARSE_BASIC_AUTH
        DEMYX_STACK_RECENT_ERRORS=$DEMYX_STACK_RECENT_ERRORS
        DEMYX_STACK_DOCKER_WATCH=$DEMYX_STACK_DOCKER_WATCH
        DEMYX_STACK_DOCKER_EXPOSED_BY_DEFAULT=$DEMYX_STACK_DOCKER_EXPOSED_BY_DEFAULT
        DEMYX_STACK_ENTRYPOINT_DEFAULTENTRYPOINTS=$DEMYX_STACK_ENTRYPOINT_DEFAULTENTRYPOINTS
        DEMYX_STACK_ACME_ONHOSTRULE=$DEMYX_STACK_ACME_ONHOSTRULE
        DEMYX_STACK_ACME_EMAIL=$DEMYX_STACK_ACME_EMAIL
        DEMYX_STACK_ACME_STORAGE=$DEMYX_STACK_ACME_STORAGE
        DEMYX_STACK_ACME_ENTRYPOINT=$DEMYX_STACK_ACME_ENTRYPOINT
        DEMYX_STACK_ACME_HTTPCHALLENGE_ENTRYPOINT=$DEMYX_STACK_ACME_HTTPCHALLENGE_ENTRYPOINT
        DEMYX_STACK_LOG_LEVEL=$DEMYX_STACK_LOG_LEVEL
        DEMYX_STACK_LOG_ACCESS=$DEMYX_STACK_LOG_ACCESS
        DEMYX_STACK_LOG_ERROR=$DEMYX_STACK_LOG_ERROR
        DEMYX_FORCE_STS_HEADER=$DEMYX_FORCE_STS_HEADER
        DEMYX_STS_SECONDS=$DEMYX_STS_SECONDS
        DEMYX_STS_INCLUDE_SUBDOMAINS=$DEMYX_STS_INCLUDE_SUBDOMAINS
        DEMYX_STS_PRELOAD=$DEMYX_STS_PRELOAD
EOF
    sed -i 's/        //' "$DEMYX_STACK"/.env
}
