# Demyx
# https://demyx.sh
# 
# demyx list <args>
#
demyx_list() {
    while :; do
        case "$2" in
            update)
                DEMYX_LIST_UPDATE=1
                ;;
            --json)
                DEMYX_LIST_JSON=1
                ;;
            --raw)
                DEMYX_LIST_RAW=1
                ;;
            --)
                shift
                break
                ;;
            -?*)
                printf '\e[31m[CRITICAL]\e[39m Unknown option: %s\n' "$2" >&2
                exit 1
                ;;
            *)
                break
        esac
        shift
    done

    cd "$DEMYX_WP" || exit

    if [[ -n "$DEMYX_LIST_UPDATE" ]]; then
        source "$DEMYX"/.update_local
        source "$DEMYX"/.update_remote
        PRINT_TABLE="DEMYX^ CURRENT^ UPDATE\n"
        PRINT_TABLE+="BUILD^ $DEMYX_LOCAL_VERSION^ $([[ "$DEMYX_LOCAL_VERSION" != "$DEMYX_REMOTE_VERSION" ]] && echo "$DEMYX_REMOTE_VERSION")\n"
        PRINT_TABLE+="BROWSERSYNC^ $DEMYX_LOCAL_BROWSERSYNC_VERSION^ $([[ "$DEMYX_LOCAL_BROWSERSYNC_VERSION" != "$DEMYX_REMOTE_BROWSERSYNC_VERSION" ]] && echo "$DEMYX_REMOTE_BROWSERSYNC_VERSION")\n"
        PRINT_TABLE+="CODE^ $DEMYX_LOCAL_CODE_VERSION^ $([[ "$DEMYX_LOCAL_CODE_VERSION" != "$DEMYX_REMOTE_CODE_VERSION" ]] && echo "$DEMYX_REMOTE_CODE_VERSION")\n"
        PRINT_TABLE+="DOCKER-COMPOSE^ $DEMYX_LOCAL_DOCKER_COMPOSE_VERSION^ $([[ "$DEMYX_LOCAL_DOCKER_COMPOSE_VERSION" != "$DEMYX_REMOTE_DOCKER_COMPOSE_VERSION" ]] && echo "$DEMYX_REMOTE_DOCKER_COMPOSE_VERSION")\n"
        PRINT_TABLE+="DOCKER-SOCKET-PROXY^ $DEMYX_LOCAL_HAPROXY_VERSION^ $([[ "$DEMYX_LOCAL_HAPROXY_VERSION" != "$DEMYX_REMOTE_HAPROXY_VERSION" ]] && echo "$DEMYX_REMOTE_HAPROXY_VERSION")\n"
        PRINT_TABLE+="LOGROTATE^ $DEMYX_LOCAL_LOGROTATE_VERSION^ $([[ "$DEMYX_LOCAL_LOGROTATE_VERSION" != "$DEMYX_REMOTE_LOGROTATE_VERSION" ]] && echo "$DEMYX_REMOTE_LOGROTATE_VERSION")\n"
        PRINT_TABLE+="MARIADB^ $DEMYX_LOCAL_MARIADB_VERSION^ $([[ "$DEMYX_LOCAL_MARIADB_VERSION" != "$DEMYX_REMOTE_MARIADB_VERSION" ]] && echo "$DEMYX_REMOTE_MARIADB_VERSION")\n"
        PRINT_TABLE+="NGINX^ $DEMYX_LOCAL_NGINX_VERSION^ $([[ "$DEMYX_LOCAL_NGINX_VERSION" != "$DEMYX_REMOTE_NGINX_VERSION" ]] && echo "$DEMYX_REMOTE_NGINX_VERSION")\n"
        PRINT_TABLE+="OPENLITESPEED^ $DEMYX_LOCAL_OPENLITESPEED_VERSION^ $([[ "$DEMYX_LOCAL_OPENLITESPEED_VERSION" != "$DEMYX_REMOTE_OPENLITESPEED_VERSION" ]] && echo "$DEMYX_REMOTE_OPENLITESPEED_VERSION")\n"
        PRINT_TABLE+="OPENLITESPEED-LSPHP^ $DEMYX_LOCAL_OPENLITESPEED_LSPHP_VERSION^ $([[ "$DEMYX_LOCAL_OPENLITESPEED_LSPHP_VERSION" != "$DEMYX_REMOTE_OPENLITESPEED_LSPHP_VERSION" ]] && echo "$DEMYX_REMOTE_OPENLITESPEED_LSPHP_VERSION")\n"
        PRINT_TABLE+="SSH^ $DEMYX_LOCAL_OPENSSH_VERSION^ $([[ "$DEMYX_LOCAL_OPENSSH_VERSION" != "$DEMYX_REMOTE_OPENSSH_VERSION" ]] && echo "$DEMYX_REMOTE_OPENSSH_VERSION")\n"
        PRINT_TABLE+="TRAEFIK^ $DEMYX_LOCAL_TRAEFIK_VERSION^ $([[ "$DEMYX_LOCAL_TRAEFIK_VERSION" != "$DEMYX_REMOTE_TRAEFIK_VERSION" ]] && echo "$DEMYX_REMOTE_TRAEFIK_VERSION")\n"
        PRINT_TABLE+="UTILITIES^ $DEMYX_LOCAL_UTILITIES_VERSION^ $([[ "$DEMYX_LOCAL_UTILITIES_VERSION" != "$DEMYX_REMOTE_UTILITIES_VERSION" ]] && echo "$DEMYX_REMOTE_UTILITIES_VERSION")\n"
        PRINT_TABLE+="WORDPRESS^ $DEMYX_LOCAL_WORDPRESS_VERSION^ $([[ "$DEMYX_LOCAL_WORDPRESS_VERSION" != "$DEMYX_REMOTE_WORDPRESS_VERSION" ]] && echo "$DEMYX_REMOTE_WORDPRESS_VERSION")\n"
        PRINT_TABLE+="WORDPRESS-CLI^ $DEMYX_LOCAL_WORDPRESS_CLI_VERSION^ $([[ "$DEMYX_LOCAL_WORDPRESS_CLI_VERSION" != "$DEMYX_REMOTE_WORDPRESS_CLI_VERSION" ]] && echo "$DEMYX_REMOTE_WORDPRESS_CLI_VERSION")\n"
        PRINT_TABLE+="WORDPRESS-PHP^ $DEMYX_LOCAL_WORDPRESS_PHP_VERSION^ $([[ "$DEMYX_LOCAL_WORDPRESS_PHP_VERSION" != "$DEMYX_REMOTE_WORDPRESS_PHP_VERSION" ]] && echo "$DEMYX_REMOTE_WORDPRESS_PHP_VERSION")\n"
        PRINT_TABLE+="WORDPRESS-BEDROCK^ $DEMYX_LOCAL_WORDPRESS_BEDROCK_VERSION^ $([[ "$DEMYX_LOCAL_WORDPRESS_BEDROCK_VERSION" != "$DEMYX_REMOTE_WORDPRESS_BEDROCK_VERSION" ]] && echo "$DEMYX_REMOTE_WORDPRESS_BEDROCK_VERSION")"
        demyx_execute -v demyx_table "$PRINT_TABLE"
    elif [[ -n "$DEMYX_LIST_JSON" ]]; then
        for i in *
        do
            DEMYX_LIST_JSON_ARRAY+="\"$i\","
        done
        echo -e "{$DEMYX_LIST_JSON_ARRAY}" | sed 's/\(.*\),/\1/'
    elif [[ -n "$DEMYX_LIST_RAW" ]]; then
        for i in *
        do
            echo "$i"
        done
    else
        demyx_wp_check_empty true
        DEMYX_LIST_WP_COUNT="$(find * -maxdepth 0 -type d | wc -l)"
        PRINT_TABLE="DEMYX^ WORDPRESS ($DEMYX_LIST_WP_COUNT)\n"
        for i in *
        do
            PRINT_TABLE+="^ $i\n"
        done
        demyx_execute -v demyx_table "$PRINT_TABLE"
    fi
}
