#!/bin/bash
# Demyx
# https://github.com/demyxco/demyx
source /srv/demyx/etc/.env

DOMAIN=$1
ADMIN_USER=$2
ADMIN_PASSWORD=$3
CACHE=$4
FORCE=$5
CONTAINER_PATH="$APPS"/"$DOMAIN"
CONTAINER_NAME=${DOMAIN//./_}
WP_ID=$(uuidgen | awk -F '[-]' '{print $1}')
WP=${DOMAIN//./}_wp_${WP_ID}_1
DB=${DOMAIN//./}_db_${WP_ID}_1

if [ -f "$CONTAINER_PATH"/.env ]; then
    NO_UPDATE=$(grep -r "AUTO GENERATED" "$APPS"/"$DOMAIN"/.env)
    [[ -z "$NO_UPDATE" ]] && [[ -z "$FORCE" ]] && echo -e "\e[33m[WARNING]\e[39m Skipped .env" && exit 1
fi

if [ -n "$ADMIN_USER" ] && [ -n "$ADMIN_PASSWORD" ]; then
    WORDPRESS_USER="$ADMIN_USER"
    WORDPRESS_USER_PASSWORD="$ADMIN_PASSWORD"
else
    WORDPRESS_USER=$(docker run -it --rm demyx/utilities sh -c "gpw 1 10" | sed -e 's/\r//g')
    WORDPRESS_USER_PASSWORD=$(docker run -it --rm demyx/utilities sh -c "pwgen -cns 50 1" | sed -e 's/\r//g')
fi

[[ "$CACHE" != on ]] && CACHE=off

WORDPRESS_DB_HOST=$DB
WORDPRESS_DB_NAME=$CONTAINER_NAME
WORDPRESS_DB_USER=$CONTAINER_NAME
WORDPRESS_DB_PASSWORD=$(docker run -it --rm demyx/utilities sh -c "pwgen -cns 50 1" | sed -e 's/\r//g')
MARIADB_ROOT_PASSWORD=$(docker run -it --rm demyx/utilities sh -c "pwgen -cns 50 1" | sed -e 's/\r//g')

if [ -f "$CONTAINER_PATH"/.env ]; then
    source "$CONTAINER_PATH"/.env
fi

cat > "$CONTAINER_PATH"/.env <<-EOF
# AUTO GENERATED
# To override, see demyx -h

WP_ID=$WP_ID
DOCKER_COMPOSE_VERSION=$DOCKER_COMPOSE_VERSION
CONTAINER_PATH=$CONTAINER_PATH
CONTAINER_NAME=$CONTAINER_NAME
DOMAIN=$DOMAIN
WP=$WP
DB=$DB
ACCESS_LOG=$LOGS/$DOMAIN.access.log
ERROR_LOG=$LOGS/$DOMAIN.error.log
WORDPRESS_USER=$WORDPRESS_USER
WORDPRESS_USER_PASSWORD=$WORDPRESS_USER_PASSWORD
WORDPRESS_DB_HOST=db_${WP_ID}
WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
WORDPRESS_DB_USER=$WORDPRESS_DB_USER
WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
MARIADB_DEFAULT_CHARACTER_SET=utf8
MARIADB_CHARACTER_SET_SERVER=utf8
MARIADB_COLLATION_SERVER=utf8_general_ci
MARIADB_KEY_BUFFER_SIZE=32M
MARIADB_MAX_ALLOWED_PACKET=16M
MARIADB_TABLE_OPEN_CACHE=2000
MARIADB_SORT_BUFFER_SIZE=4M
MARIADB_NET_BUFFER_SIZE=4M
MARIADB_READ_BUFFER_SIZE=2M
MARIADB_READ_RND_BUFFER_SIZE=1M
MARIADB_MYISAM_SORT_BUFFER_SIZE=32M
MARIADB_LOG_BIN=mysql-bin
MARIADB_BINLOG_FORMAT=mixed
MARIADB_SERVER_ID=1
MARIADB_INNODB_DATA_FILE_PATH=ibdata1:10M:autoextend
MARIADB_INNODB_BUFFER_POOL_SIZE=32M
MARIADB_INNODB_LOG_FILE_SIZE=5M
MARIADB_INNODB_LOG_BUFFER_SIZE=8M
MARIADB_INNODB_FLUSH_LOG_AT_TRX_COMMIT=1
MARIADB_INNODB_LOCK_WAIT_TIMEOUT=50
MARIADB_INNODB_USE_NATIVE_AIO=1
MARIADB_READ_BUFFER=2M
MARIADB_WRITE_BUFFER=2M
MARIADB_MAX_CONNECTIONS=100
FORCE_STS_HEADER=$FORCE_STS_HEADER
STS_SECONDS=$STS_SECONDS
STS_INCLUDE_SUBDOMAINS=$STS_INCLUDE_SUBDOMAINS
STS_PRELOAD=$STS_PRELOAD
MONITOR_THRESHOLD=3
MONITOR_SCALE=5
MONITOR_CPU=25
FASTCGI_CACHE=$CACHE
EOF

echo -e "\e[32m[SUCCESS]\e[39m Generated .env"

# TODO
#SUBNET=${SUBNETS}.${SUBNET_MAJOR}.${SUBNET_MINOR}.0/24