#!/usr/bin/with-contenv bash
# Demyx
# https://demyx.sh
 
if [[ ! -d /demyx/etc ]]; then
	echo "Demyx is now installing..."
	git clone https://github.com/demyxco/demyx.git /demyx/etc
    mkdir -p /demyx/app/html
    mkdir -p /demyx/app/php
    mkdir -p /demyx/app/wp
    mkdir -p /demyx/app/stack
    mkdir -p /demyx/backup
    mkdir -p /demyx/custom
    cp /demyx/etc/example/example-callback.sh /demyx/custom
    chown -R demyx:demyx /demyx
	echo "Demyx is now installed"
fi

# Set default port if DEMYX_SSH is missing
if [[ -z "$DEMYX_SSH" ]]; then
	export DEMYX_SSH=2222
fi

# Make demyx user's .ssh directory if it isn't made yet
if [[ ! -d /home/demyx/.ssh ]]; then
    mkdir -p /home/demyx/.ssh
fi

# Prevents ssh errors from local machine
if [[ -f /home/demyx/.ssh/ssh_host_rsa_key ]]; then
	cp /home/demyx/.ssh/ssh_host_rsa_key /etc/ssh
	cp /home/demyx/.ssh/ssh_host_rsa_key.pub /etc/ssh
else
	ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa
	cp /etc/ssh/ssh_host_rsa_key /home/demyx/.ssh
	cp /etc/ssh/ssh_host_rsa_key.pub /home/demyx/.ssh
fi

# Set proper ssh permissions
if [[ -f /home/demyx/.ssh/authorized_keys ]]; then
	chmod 644 /home/demyx/.ssh/authorized_keys
fi
chmod 700 /home/demyx/.ssh
chmod 600 /etc/ssh/ssh_host_rsa_key

demyx-helper "$DEMYX_MODE"
